name: 'Generate memory estimates'
description: 'Generate library size tables for doxygen.'
inputs:
  path:
    description: 'Path to library directory.'
    required: false
    default: ./
  lib_name:
    description: 'Library name for table header.'
    required: true
  src:
    description: 'Files to measure size of, newline delimited.'
    required: true
  include:
    description: 'Include directories, newline delimited.'
    required: true
  compiler_flags:
    description: 'Extra compiler flags, newline delimited.'
    required: false
    default: ''
  output:
    description: 'File to write generated table to.'
    required: false
    default: 'size_table.html'
  toolchain_link:
    description: 'Link to ARM GCC tar.bz2 to use for compiling files (default version 9-2020-q2).'
    required: false
    default: "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2?revision=05382cca-1721-44e1-ae19-1e7c3dc96118&la=en&hash=D7C9D18FCA2DD9F894FD9F3C3DC9228498FA281A"
runs:
  using: "composite"
  steps:
    - name: Install ARM GCC
      run: |
          wget -qO- "${{ inputs.toolchain_link }}" | sudo tar --strip-components=1 -xj -C /usr/local
      shell: bash
    - name: Compute sizes
      working-directory: ${{ inputs.path }}
      run: >-
          ${{ github.action_path }}/memory_statistics.py
          --name "${{ inputs.lib_name }}"
          --sources "${{ inputs.src }}"
          --includes "${{ inputs.include }}"
          --flags "${{ inputs.compiler_flags }}"
          --output "${{ inputs.output }}"
      shell: bash
