name: 'formatting'
description: 'CI formatting check'
inputs:
  path:
    description: 'Path to repository folder to run formatting check for.'
    required: false
    default: ./
  exclude-files:
    description: 'List of comma-separated files to exclude from trailing whitespace check. Eg file1,file2'
    required: false
    default: ''
  exclude-dirs:
    description: 'List of comma-separated directories to exclude from trailing whitespace formatting check. Eg docs,build'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
      - env:
          bashPass: \033[32;1mPASSED -
          bashInfo: \033[33;1mINFO -
          bashFail: \033[31;1mFAILED -
          bashEnd:  \033[0m
          stepName: Install Uncrustify
        shell: bash
        run: |
          # ${{ env.stepName }}
          echo "::group::${{ env.stepName }}"
          sudo apt-get install uncrustify
          echo "::endgroup::"

      - env:
          stepName: Validate Inputs
          # The bash escape character is \033
          # At time of writing, you can't add a global environment
          # to an action file so stuck with this. If this gets changed
          # Please move this
          bashPass:   \033[32;1mPASSED -
          bashInfo:   \033[33;1mINFO -
          bashFail:   \033[31;1mFAILED -
          bashEnd:    \033[0m
        name: ${{ env.stepName }}
        id: validate-inputs
        shell: bash
        run: |
          # ${{ env.stepName }}
          exitStatus=0
          # Check exclude dirs for possible input issues
          if [[ "${{ inputs.exclude-dirs }}" = *" "* ]]; then
            echo -e "${{ env.bashFail }} YOU HAVE WHITESPACE IN YOUR EXCLUDE-DIRS. ${{ env.bashEnd }}"
            exitStatus=1
          fi

          # Check exclude-files  for possible input issues
          if [[ "${{ inputs.exclude-files }}" = *" "* ]]; then
            echo -e "${{ env.bashFail }} YOU HAVE WHITESPACE IN YOUR EXCLUDE-FILES. ${{ env.bashEnd }}"
            exitStatus=1
          fi
          exit $exitStatus

      - env:
          bashPass: \033[32;1mPASSED -
          bashInfo: \033[33;1mINFO -
          bashFail: \033[31;1mFAILED -
          bashEnd:  \033[0m
          stepName: Run Uncrustify
        name: ${{ env.stepName }}
        if: ${{ steps.validate-inputs.outcome}} = "success"
        working-directory: ${{ inputs.path }}
        shell: bash
        run: |
          # ${{ env.stepName }}
          echo -e "${{ env.bashInfo }} Using Uncrustify version "$(uncrustify --version)" ${{ env.bashEnd }}"
          echo "::group::${{ env.stepName }}"

          # GitHub automatically use "set -e" which causes scripts to fail on the first exit code
          # This would mean the first time a file fails the check that we exit without formatting all files.
          set +e

          # Get all files that end in .c or .h.
          # Exclude any files or directories that we were asked to.
          # Then limit the search to files that have the amazon copyright on them.
          # -l Provides a list of the files
          # -r Means do a recursive search
          # -i tells it to ignore the case
          files=$(grep --include={*.[ch],} --exclude={${{inputs.exclude-files}},} --exclude-dir={${{inputs.exclude-dirs}},} -lriE "copyright (.*) [0-9]{4} amazon.com" )

          # Loop over the files that matched the above conditions
          for file in ${files[@]}; do
            # Print them out for future debugging
            echo -e "${{ env.bashInfo }} Parsing File: "$file" ${{ env.bashEnd }}"

            # Pipe the output of the command to a variable
            # This way we can print the command only if it fails
            fileOut=$(uncrustify --no-backup --replace --if-changed -c $GITHUB_ACTION_PATH/uncrustify.cfg -l C $file 2>&1)

            # If the previous command failed then print out an error message as well as the output
            if [ "$?" != "0" ]; then
              echo -e "${{ env.bashFail }} Error parsing "$file" ${{ env.bashEnd }}"
              echo -e "$fileOut"
            fi
          done
          echo "::endgroup::"

          # Run a git diff to print the differences if any exist, return an error code if there are any
          echo "::group::File Difference"
          git diff --exit-code
          exitCode=$?
          echo "::endgroup::"
          if [ "$exitCode" = "0" ]; then
            echo -e "${{ env.bashPass }} ${{env.stepName }} ${{ env.bashEnd }}"
          else
            filesWithErrors=$(git diff --name-only)
            echo -e "${{ env.bashFail }} List of files with formatting errors: ${{ env.bashEnd }}"
            echo -e "${{ env.bashFail }} "$filesWithErrors" ${{ env.bashEnd }} "
            echo -e "${{ env.bashFail }} ${{env.stepName }} ${{ env.bashEnd }}"
            # If there is an error, set this flag high again so the exit 1 fails the run instantly
            set -e
            exit 1
          fi

      - env:
          bashPass: \033[32;1mPASSED -
          bashInfo: \033[33;1mINFO -
          bashFail: \033[31;1mFAILED -
          bashEnd:  \033[0m
          stepName: Check For Trailing Whitespace
        name: ${{ env.stepName }}
        shell: bash
        # Use this so that even if we fail formatting these checks run
        # Solves the issue of "Make commit to fix formatting, to then learn
        # You need to fix whitespace
        if: success() || failure() && ${{ steps.validate-inputs.outcome}} = "success"
        working-directory: ${{ inputs.path }}
        run: |
          # ${{ env.stepName }}
          set +e
          grep --exclude={README.md,${{inputs.exclude-files}},} --exclude-dir={${{inputs.exclude-dirs}},.git} -rnIe "[[:blank:]]$" .
          if [ "$?" = "0" ]; then
            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
            set -e
            exit 1
          else
            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
            exit 0
          fi

      - env:
          bashPass: \033[32;1mPASSED -
          bashInfo: \033[33;1mINFO -
          bashFail: \033[31;1mFAILED -
          bashEnd:  \033[0m
          stepName: Check for CRLF
        name: ${{ env.stepName }}
        if: success() || failure() && ${{ steps.validate-inputs.outcome}} = "success"
        working-directory: ${{ inputs.path }}
        shell: bash
        run: |
          # ${{ env.stepName }}
          set +e
          grep --exclude={${{inputs.exclude-files}},} --exclude-dir={${{inputs.exclude-dirs}},.git} -rnl $'\r'
          if [ "$?" = "0" ]; then
            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
            set -e
            exit 1
          else
            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
            exit 0
          fi
