name: 'Localhost Echo Server'
description: 'Starts an echo server using Python.'

inputs:
  host_address:
    description: "Host address for echo server."
    required: false
    default: "127.0.0.1"
  port_number:
    description: "Port for echo server."
    required: True

runs:
  using: "composite"
  steps:
    - name: Run localhost Echo server
      shell: bash
      run: |
        python3 --version
        # Use the host_address input if provided, otherwise default to 127.0.0.1
        HOST=${{ inputs.host_address }}
        if [[ -z "$HOST" ]]; then
          HOST="127.0.0.1"
        fi
        python3 $GITHUB_ACTION_PATH/local_echo_server.py --host=$HOST --port_number=${{ inputs.port_number }} &

