name: 'Localhost Echo Server'
description: 'Starts an echo server using GoLang.'

inputs:
  port_number:
    description: "Port for echo server."
    required: True

runs:
  using: "composite"
  steps: 
      - uses: actions/setup-go@v4
      - name: Run localhost Echo server
        run: |
          go version
          go run $GITHUB_ACTION_PATH/local_echo_server.go ${{ inputs.port_number }} &
        shell: bash
