#!/bin/bash
#
# ablexicon - Compare an input list of words against a dictionary and
# optional lexicon.  If any words are in neither the dictionary nor the
# lexicon, log them to stdout.
#
set -e
set -f

function usage () {
    echo "Find occurrences of non-dictionary/lexicon words"
    echo ""
    echo "Usage:"
    echo " ${0##*/} [options]"
    echo ""
    echo "Options:"
    echo " -f, --file         source text (defaults to /dev/fd/0)"
    echo " -l, --lexicon      lexicon file (one word per line)"
    echo " -h, --help         display this help"
    exit 1
}

#
# Verify that required commands are present
#
REQUIRED=( "spell" "getopt" )
for i in "${REQUIRED[@]}"
do
    command -v $i"" >/dev/null
    if [ $? -ne "0" ]
    then
        echo "'"$i"' must be installed, exiting...">&2
        exit 1
    fi
done

GETOPT_OUT=`getopt -o hf:l: --long help,file:,lexicon: -n "${0##*/}" -- "$@"`
if [ $? != 0 ]
then
    echo "Exiting..." >&2
    exit 1
fi

eval set -- "$GETOPT_OUT"

INFILE=/dev/fd/0
LEXICON=/dev/null
while true; do
  case "$1" in
    -h | --help ) usage $0 ;;
    -f | --file ) INFILE="$2"; shift 2 ;;
    -l | --lexicon ) LEXICON="$2"; shift 2 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

if [ ! -f $INFILE"" ] && [ $INFILE"" != /dev/fd/0 ]
then
    echo "Invalid input file"
    usage
fi
#
# Read the lexicon into an array
#
readarray -t lexicon < $LEXICON""
lexicon_size="${#lexicon[@]}"

#
# Search for all input words, sort them removing duplicate words in
# the process and then find them in the dictionary.
#
for word in `cat $INFILE"" | sort -u | spell`
do
    #
    # Search for each remaining word in the lexicon
    #
    if [ $LEXICON"" != /dev/null ]
    then
        if ! grep -w -q "$word" $LEXICON""
        then
            #
            # The word is neither in the dictionary nor the lexicon, send
            # it to stdout.
            #
            echo $word
        fi
    else
        # if the lexicon is /dev/null i.e. it is not provided by the user,
        # then we should just echo the word.
        echo $word
    fi
done

exit 0
