name: 'Core Library Release Rollback'
description: 'Mark a GitHub release as broken without deleting tags or resetting commits'
inputs:
  version_number:
    description: 'Release Version Number to mark as broken (e.g., v1.0.0)'
    required: true
  github_token:
    description: 'GitHub token for operations'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  env:
    VERSION_NUMBER: ${{ inputs.version_number }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
  steps:
    - name: Mark release as broken
      shell: bash
      run: |
        if gh release view $VERSION_NUMBER >/dev/null 2>&1; then
          # Get current release info
          CURRENT_TITLE=$(gh release view $VERSION_NUMBER --json name --jq '.name')
          CURRENT_BODY=$(gh release view $VERSION_NUMBER --json body --jq '.body')
          
          # Update release with broken warnings
          NEW_TITLE="$CURRENT_TITLE [DEPRECATED - DO NOT USE]"
          NEW_BODY="⚠️ **DO NOT USE - BROKEN RELEASE** ⚠️

This release contains critical issues and has been marked as broken.
Please use a newer version instead.

---
Original Release Notes:
$CURRENT_BODY"
          
          # Update the release
          gh release edit $VERSION_NUMBER \
            --title "$NEW_TITLE" \
            --notes "$NEW_BODY" \
            --prerelease
          
          echo "Successfully marked release $VERSION_NUMBER as broken"
        else
          echo "Release $VERSION_NUMBER does not exist"
        fi
