name: 'generate-sbom'
description: 'Generate SBOM for FreeRTOS libraries'
inputs:
  path:
    description: 'Path to repository folder containing manifest.yml to verify.'
    required: false
    default: ./
  source_path:
    description: 'Path to source code'
    required: false
    default: ./source
  url:
    description: 'github url to the repo'
    required: false
    default: 'https://github.com/FreeRTOS'
runs:
  using: "composite"
  steps:
      - name: Install dependencies
        run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
        shell: bash 
      - name: Run generator script
        working-directory: ${{ inputs.path }}
        run: |
          python3 $GITHUB_ACTION_PATH/scan_dir.py --source-path ${{ inputs.source_path }} --url ${{ inputs.url }}
        shell: bash
