name: 'generate-sbom'
description: 'Generate SBOM for corePKCS11 library'
inputs:
  path:
    description: 'Path to repository folder containing manifest.yml to verify.'
    required: false
    default: ./
  token:
    description: 'Token'
    required: false
    default: ${{ github.token }}
  script:
    description: 'Python script for the specific library'
    required: True
runs:
  using: "composite"
  steps:
      - name: Install dependencies
        run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
        shell: bash 
      - name: Run generator script
        working-directory: ${{ inputs.path }}
        run: |
          python3 $GITHUB_ACTION_PATH/${{ inputs.script }}
        shell: bash
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-sbom
          token: ${{ inputs.token }}
          path: ${{ inputs.path }}
          commit-message: Add sbom file
          title: 'Add sbom file'
          body: >
            This PR is auto-generated by
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
