name: 'generate-sbom'
description: 'Generate SBOM for FreeRTOS libraries'
inputs:
  path:
    description: 'Path to repository folder containing manifest.yml to verify.'
    required: false
    default: ./
  token:
    description: 'Token'
    required: false
    default: ${{ github.token }}
  script:
    description: 'Python script for the specific library'
    required: True
runs:
  using: "composite"
  steps:
      - name: Install dependencies
        run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
        shell: bash 
      - name: Run generator script
        working-directory: ${{ inputs.path }}
        run: |
          python3 $GITHUB_ACTION_PATH/${{ inputs.script }}
        shell: bash
