name: 'executable-monitor'
description: 'Runs and executable until a termination line is hit or a timeout occurs. Reports if the executable completed successfully or failed.'
inputs:
  exe-path:
    description: 'Path to the executable to run.'
    required: true
  log-dir:
    description: 'Path to directory to store logs.'
    required: true
  success-line:
    description: 'Line of output from executable indicating success.'
    required: false
    default: "Demo completed successfully."
  timeout-seconds:
    description: 'Maximum amount of time to run the executable. Default is 600.'
    required: false
    default: 600
  number-of-runs:
    description: 'Number of times to run the executable.'
    required: false
    default: 1

runs:
  using: "composite"
  steps: 
      - name: Install dependencies
        run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
        shell: bash
      - name: Run executable with monitoring script
        run: python3 $GITHUB_ACTION_PATH/executable-monitor.py --exe-path=${{ inputs.exe-path }} --timeout-seconds=${{ inputs.timeout-seconds }} --number-of-runs=${{ inputs.number-of-runs }} --success-line="${{ inputs.success-line }}" --log-dir=${{ inputs.log-dir }}
        shell: bash
