name: 'formatting'
description: 'CI formatting check'
inputs:
  path:
    description: 'Path to repository folder to run formatting check for.'
    required: false
    default: ./
  exclude-files:
    description: 'List of comma-separated files to exclude from formatting check. Eg file1,file2'
    required: false
    default: ''
  exclude-dirs:
    description: 'List of comma-separated directories to exclude from formatting check. Eg docs,build'
    required: false
    default: ''
runs:
  using: "composite"
  steps: 
      - name: Install Uncrustify
        run: sudo apt-get install uncrustify
        shell: bash
      - name: Run Uncrustify
        working-directory: ${{ inputs.path }}
        run: |
          # Run uncrustify on C files while ignoring symlinks.
          find . -iname "*.[hc]" -type f -exec uncrustify --check -c $GITHUB_ACTION_PATH/uncrustify.cfg -l C {} +
        shell: bash
      - name: Check For Trailing Whitespace
        working-directory: ${{ inputs.path }}
        run: |
          set +e
          grep --exclude={README.md,${{ inputs.exclude-files }}} --exclude-dir={${{ inputs.exclude-dirs }},''} -rnI -e "[[:blank:]]$" .
          if [ "$?" = "0" ]; then
            echo "Files have trailing whitespace."
            exit 1
          else
            exit 0
          fi
        shell: bash
      - name: Check for CRLF
        working-directory: ${{ inputs.path }}
        run: |
          set +e
          find . -path ./.git -prune -o -exec file {} + |  grep "CRLF"
          if [ "$?" = "0" ]; then
            echo "Files have CRLF line endings."
            exit 1
          else
            exit 0
          fi
        shell: bash
