name: 'spellings'
description: 'cSpell CI spelling check'
inputs:
  path:
    description: 'Path to repository folder to check spellings in.'
    required: false
    default: ./
  exclude-dirs:
    description: "Comma separated list of directories to not spell check"
    required: false
  exclude-files:
    description: "Comma separated list of files to not spell check"
    required: false
  include-extensions:
    description: "Comma separated list of files to match to regex"
    required: false


runs:
  using: "composite"
  steps:
    - env:
        bashPass: \033[32;1mPASSED -
        bashInfo: \033[33;1mINFO -
        bashFail: \033[31;1mFAILED -
        bashEnd:  \033[0m
        stepName: Set-Up The Spell Checker
      name: ${{ env.stepName }}
      id: spell-checker-setup
      shell: bash
      run: |
        # ${{ env.stepName }}
        echo "::group::Install Dependencies"

        # Install the Dependencies we need to run the spell-checker
        sudo apt-get install util-linux -y
        sudo apt-get install fd-find -y
        sudo apt-get install npm -y
        sudo npm install -g cspell
        echo "::endgroup::"

        # Add the current directory to PATH
        export PATH="$GITHUB_ACTION_PATH:$PATH"

        # cp has an error code if it's asked to copy to the same file
        # Wrap it in a set +e in case the input path is the working directory
        set +e
        cp $GITHUB_ACTION_PATH/cspell.config.yaml ${{ inputs.path }}
        set -e


        # Make sure we have all the commands we need.
        echo -e "${{ env.bashInfo }} fdfind --version ${{ env.bashEnd }}"
        echo -e "${{ env.bashInfo }} cspell --version ${{ env.bashEnd }}"

        # Only reach this line if no errors were hit above
        echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"

    - env:
        bashPass: \033[32;1mPASSED -
        bashInfo: \033[33;1mINFO -
        bashFail: \033[31;1mFAILED -
        bashEnd:  \033[0m
        stepName: Spell Checker
      name: ${{ env.stepName }}
      id: run-spell-checker
      working-directory: ${{ inputs.path }}
      shell: bash
      run: |
        # ${{ env.stepName }}
        #echo "::group::${{ env.stepName }}"
        export PATH="$GITHUB_ACTION_PATH:$PATH"

        # Add helper script to path
        export PATH="$PATH:$GITHUB_ACTION_PATH"

        # Get all files
        files=$(getFiles --exclude-dirs="${{ inputs.exclude-dirs }}" --exclude-files="${{ inputs.exclude-files }}" --include-extensions="${{ inputs.include-extensions}}")

        # Wrap the check in set +e so it runs against all files
        set +e
        exitStatus=0
        for file in ${files[@]}; do
          cspell --language-id C --color -c cspell.config.yaml --show-suggestions --show-context "$file"
          if ! [ $? -eq 0 ]; then
            exitStatus=1
          fi
        done
        set -e

        echo "::endgroup::"
        if [ $exitStatus -eq 0 ]; then
          echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
        else
          echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
          exit 1
        fi
