name: 'Core Library Release'
description: 'Universal release action for FreeRTOS core libraries'
inputs:
  version_number:
    description: 'Release Version Number (e.g., v1.0.0)'
    required: true
  branch:
    description: 'Branch to release from'
    required: false
    default: 'main'
  delete_existing_tag_release:
    description: 'Is this a re-release of existing tag/release? (Default: false)'
    default: 'false'
    required: false
  github_token:
    description: 'GitHub token for creating releases'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Check if tag exists
      if: ${{ inputs.delete_existing_tag_release == 'true' }}
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git fetch origin
        if git tag --list $VERSION_NUMBER
        then
            echo "Deleting existing tag for $VERSION_NUMBER"
            git push origin --delete tags/$VERSION_NUMBER
        fi

    - name: Check if release exists
      if: ${{ inputs.delete_existing_tag_release == 'true' }}
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 23F3D4EA75716059
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt-get install gh
        if gh release list | grep $VERSION_NUMBER
        then
            echo "Deleting existing release for $VERSION_NUMBER"
            gh release delete --yes $VERSION_NUMBER
        fi

    - name: Configure git identity
      shell: bash
      env:
        GITHUB_ACTOR: ${{ github.actor }}
      run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email $GITHUB_ACTOR@users.noreply.github.com

    - name: Update version number in manifest.yml
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        BRANCH: ${{ inputs.branch }}
      run: |
        if [ -f "./manifest.yml" ]; then
          sed -i -b "0,/^version/s/^version.*/version: \"$VERSION_NUMBER\"/g" ./manifest.yml
          git add manifest.yml
          git commit -m '[AUTO][RELEASE]: Update version number in manifest.yml'
          git push origin "$BRANCH"
        fi

    - name: Update version number in doxygen
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        BRANCH: ${{ inputs.branch }}
      run: |
        if [ -f "./docs/doxygen/config.doxyfile" ]; then
          sed -i -b "s/PROJECT_NUMBER *=.*/PROJECT_NUMBER         = $VERSION_NUMBER/g" ./docs/doxygen/config.doxyfile
          git add docs/doxygen/config.doxyfile
          git commit -m '[AUTO][RELEASE]: Update version number in doxygen'
          git push origin "$BRANCH"
        fi

    - name: Tag and push
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        git tag "$VERSION_NUMBER" -a -m "$REPO_NAME Library $VERSION_NUMBER"
        git push origin --tags

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.version_number }}
        path: ${{ github.event.repository.name }}
        submodules: recursive

    - name: Debug source path
      shell: bash
      env:
        SOURCE_PATH: ./${{ github.event.repository.name }}
      run: |
        echo "Source path: $SOURCE_PATH"
        echo "Contents of source directory:"
        ls -la "$SOURCE_PATH"

    - name: Generate SBOM for Git Repository
      uses: jasonpcarroll/CI-CD-Github-Actions/sbom-generator@main
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        ORG_NAME: ${{ github.repository_owner }}
        VERSION_NUMBER: ${{ inputs.version_number }}
      with:
        directory: "./$REPO_NAME"
        distribution-type: repository
        creator: Amazon Web Services, Inc.
        download-location: "git+https://github.com/$ORG_NAME/$REPO_NAME@$VERSION_NUMBER"
        homepage: "https://www.github.com/$ORG_NAME/$REPO_NAME"
        namespace-prefix: "https://github.com/$REPO_NAME/releases/download/$VERSION_NUMBER/"

    - name: Remove hidden files and directories from repo to make zip archive
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: |
        find $REPO_DIR -type f -name ".*" -delete
        find $REPO_DIR -type d -name ".*" -delete

    - name: Validate that the tests still build and pass.
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: |
          sudo apt-get install -y lcov
          cmake -S $REPO_DIR/test -B build/ \
          -G "Unix Makefiles" \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_CLONE_SUBMODULES=ON \
          -DCMAKE_C_FLAGS='--coverage -Wall -Wextra -Werror'
          make -C build/ all
          cd build/
          ctest -E system --output-on-failure
          cd ..

    - name: Remove test directory from repo to make zip archive
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: |
        rm -rf "$REPO_DIR/test"

    - name: Update README.md to remove testing information.
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: sed -i '/^## Building Unit Tests$/,/^## Reference examples$/{/^## Reference examples$/!d;} ; /^## CBMC$/,/^## Reference examples$/{/^## Reference examples$/!d;}' $REPO_DIR/README.md   

    - name: Generate SBOM for ZIP archive
      uses: jasonpcarroll/CI-CD-Github-Actions/sbom-generator@main
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        ORG_NAME: ${{ github.repository_owner }}
        VERSION_NUMBER: ${{ inputs.version_number }}
      with:
        directory: "./$REPO_NAME"
        distribution-type: archive
        creator: Amazon Web Services, Inc.
        download-location: "https://github.com/$REPO_NAME/releases/download/$VERSION_NUMBER/$REPO_NAME-$VERSION_NUMBER.zip"
        homepage: "https://www.github.com/$ORG_NAME/$REPO_NAME"
        namespace-prefix: "https://github.com/$REPO_NAME/releases/download/$VERSION_NUMBER/"

    - name: Copy ZIP Archive SBOMs into repository folder
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
        VERSION_NUMBER: ${{ inputs.version_number }}
      run: |
        cp *archive-SPDX* $REPO_DIR
    
    - name: Install ZIP tools
      shell: bash
      run: sudo apt-get install zip unzip
    
    - name: Create ZIP
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        REPO_DIR: ./${{ github.event.repository.name }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        zip -r "$REPO_NAME-$VERSION_NUMBER.zip" "$REPO_DIR"

    - name: Deploy doxygen documentation
      uses: FreeRTOS/CI-CD-Github-Actions/doxygen-generation@main
      with:
        ref: ${{ inputs.version_number }}
        add_release: "true"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ inputs.version_number }}
        release_name: ${{ inputs.version_number }}
        body: Release ${{ inputs.version_number }} of the ${{ github.event.repository.name }} Library.
        draft: false
        prerelease: false

    - name: Upload ZIP Archive Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPO_NAME: ${{ github.event.repository.name }}
        VERSION_NUMBER: ${{ inputs.version_number }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.REPO_NAME }}-${{ env.VERSION_NUMBER }}.zip
        asset_name: ${{ env.REPO_NAME }}-${{ env.VERSION_NUMBER }}.zip
        asset_content_type: application/zip

    - name: Generate SBOM file matrix
      id: sbom_matrix
      shell: bash
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        VERSION_NUMBER: ${{ inputs.version_number }}
      run: |
        files=$(find . -name "*.spdx*" -type f -printf '%f\n' | jq -R -s -c 'split("\n")[:-1]')
        echo "matrix={\"file\":$files}" >> $GITHUB_OUTPUT

    - name: Upload SBOM Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      strategy:
        matrix: ${{ fromJson(steps.sbom_matrix.outputs.matrix) }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ matrix.file }}
        asset_name: ${{ matrix.file }}
        asset_content_type: >
          ${{ endsWith(matrix.file, '.spdx.json') && 'application/json' ||
              endsWith(matrix.file, '.spdx.xml') && 'application/xml' ||
              endsWith(matrix.file, '.spdx.yaml') && 'application/yaml' ||
              'text/plain' }}

