name: 'Core Library Release'
description: 'Universal release action for FreeRTOS core libraries'
inputs:
  version_number:
    description: 'Release Version Number (e.g., v1.0.0)'
    required: true
  branch:
    description: 'Branch to release from'
    required: false
    default: 'main'
  github_token:
    description: 'GitHub token for creating releases'
    required: true
    default: ${{ github.token }}
  run_test_command:
    description: 'Command to build and run tests'
    required: false
    default: 'sudo apt-get install -y lcov && cmake -S $REPO_DIR/test -B build/ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DBUILD_CLONE_SUBMODULES=ON -DCMAKE_C_FLAGS="--coverage -Wall -Wextra -Werror" && make -C build/ all && cd build/ && ctest -E system --output-on-failure && cd ..'
  repo_build_command:
    description: 'Command to build repository'
    required: false
    default: 'cmake -S $REPO_DIR -B repo-build/ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release && make -C repo-build/ all'

runs:
  using: 'composite'
  env:
    VERSION_NUMBER: ${{ inputs.version_number }}
    BRANCH: ${{ inputs.branch }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
  steps:
    - name: Capture initial commits of library and GitHub pages for rollback
      shell: bash
      run: |
        echo "INITIAL_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
        git fetch origin gh-pages:gh-pages || true
        echo "INITIAL_GHPAGES_COMMIT=$(git rev-parse gh-pages 2>/dev/null || echo 'none')" >> $GITHUB_ENV

    - name: Configure git identity
      shell: bash
      env:
        GITHUB_ACTOR: ${{ github.actor }}
      run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email $GITHUB_ACTOR@users.noreply.github.com

    - name: Update version number in manifest.yml
      shell: bash
      run: |
        if [ -f "./manifest.yml" ]; then
          sed -i -b "0,/^version/s/^version.*/version: \"$VERSION_NUMBER\"/g" ./manifest.yml
          git add manifest.yml
          git commit -m '[AUTO][RELEASE]: Update version number in manifest.yml'
          git push origin "$BRANCH"
        fi

    - name: Update version number in doxygen
      shell: bash
      run: |
        if [ -f "./docs/doxygen/config.doxyfile" ]; then
          sed -i -b "s/PROJECT_NUMBER *=.*/PROJECT_NUMBER         = $VERSION_NUMBER/g" ./docs/doxygen/config.doxyfile
          git add docs/doxygen/config.doxyfile
          git commit -m '[AUTO][RELEASE]: Update version number in doxygen'
          git push origin "$BRANCH"
        fi

    - name: Tag and push
      shell: bash
      env:
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        git tag "$VERSION_NUMBER" -a -m "$REPO_NAME Library $VERSION_NUMBER"
        git push origin --tags

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.version_number }}
        path: ${{ github.event.repository.name }}
        submodules: recursive

    - name: Debug source path
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: |
        echo "Source path: $REPO_DIR"
        echo "Contents of source directory:"
        ls -la "$REPO_DIR"

    - name: Generate SBOM for Git Repository
      uses: jasonpcarroll/CI-CD-Github-Actions/sbom-generator@main
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        ORG_NAME: ${{ github.repository_owner }}
      with:
        directory: "./$REPO_NAME"
        distribution-type: repository
        creator: Amazon Web Services, Inc.
        download-location: "git+https://github.com/$ORG_NAME/$REPO_NAME@$VERSION_NUMBER"
        homepage: "https://www.github.com/$ORG_NAME/$REPO_NAME"
        namespace-prefix: "https://github.com/$REPO_NAME/releases/download/$VERSION_NUMBER/"

    - name: Validate that the tests still build and pass.
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: ${{ inputs.run_test_command }}

    - name: Remove hidden files and directories from repo to make zip archive
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: |
        find $REPO_DIR -type f -name ".*" -delete
        find $REPO_DIR -type d -name ".*" -exec rm -rf {} +

    - name: Remove test directory from repo to make zip archive
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: |
        rm -rf "$REPO_DIR/test"

    - name: Update README.md to remove testing information.
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: sed -i '/^## Building Unit Tests$/,/^## Reference examples$/{/^## Reference examples$/!d;} ; /^## CBMC$/,/^## Reference examples$/{/^## Reference examples$/!d;}' $REPO_DIR/README.md   

    - name: Build repository with root CMakeLists.txt
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: ${{ inputs.repo_build_command }}

    - name: Generate SBOM for ZIP archive
      uses: jasonpcarroll/CI-CD-Github-Actions/sbom-generator@main
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        ORG_NAME: ${{ github.repository_owner }}
      with:
        directory: ./$REPO_NAME
        distribution-type: archive
        creator: Amazon Web Services, Inc.
        download-location: https://github.com/$REPO_NAME/releases/download/$VERSION_NUMBER/$REPO_NAME-$VERSION_NUMBER.zip
        homepage: https://www.github.com/$ORG_NAME/$REPO_NAME
        namespace-prefix: https://github.com/$REPO_NAME/releases/download/$VERSION_NUMBER/

    - name: Copy ZIP Archive SBOMs into repository folder
      shell: bash
      env:
        REPO_DIR: ./${{ github.event.repository.name }}
      run: |
        cp *archive-SPDX* $REPO_DIR
    
    - name: Install ZIP tools
      shell: bash
      run: sudo apt-get install zip unzip
    
    - name: Create ZIP
      shell: bash
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_DIR: ./${{ github.event.repository.name }}
      run: |
        zip -r "$REPO_NAME-$VERSION_NUMBER.zip" "$REPO_DIR"

    - name: Deploy doxygen documentation
      uses: FreeRTOS/CI-CD-Github-Actions/doxygen-generation@main
      with:
        ref: ${{ inputs.version_number }}
        add_release: "true"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ inputs.version_number }}
        release_name: ${{ inputs.version_number }}
        body: Release ${{ inputs.version_number }} of the ${{ github.event.repository.name }} Library.
        draft: false
        prerelease: false

    - name: Upload ZIP Archive Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPO_NAME: ${{ github.event.repository.name }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.REPO_NAME }}-${{ env.VERSION_NUMBER }}.zip
        asset_name: ${{ env.REPO_NAME }}-${{ env.VERSION_NUMBER }}.zip
        asset_content_type: application/zip

    - name: Upload SBOMs to release.
      shell: bash
      env:
        UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
      run: |
        for file in *.spdx*; do
          if [ -f "$file" ]; then
            # Determine content type
            if [[ "$file" == *.spdx.json ]]; then
              content_type="application/json"
            elif [[ "$file" == *.spdx.xml ]]; then
              content_type="application/xml"
            elif [[ "$file" == *.spdx.yaml ]]; then
              content_type="application/yaml"
            else
              content_type="text/plain"
            fi
            
            # Upload file
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: $content_type" \
              --data-binary @"$file" \
              "${UPLOAD_URL%\{*}?name=$file"
          fi
        done

    - name: Rollback on failure
      if: failure()
      uses: jasonpcarroll/CI-CD-Github-Actions/release-rollback@main
      with:
        version_number: ${{ inputs.version_number }}
        branch: ${{ inputs.branch }}
        initial_commit: ${{ env.INITIAL_COMMIT }}
        initial_ghpages_commit: ${{ env.INITIAL_GHPAGES_COMMIT }}
        github_token: ${{ inputs.github_token }}

