name: 'Core Library Release'
description: 'Universal release action for FreeRTOS core libraries'
inputs:
  version_number:
    description: 'Release Version Number (e.g., v1.0.0)'
    required: true
  branch:
    description: 'Branch to release from'
    required: false
    default: 'main'
  delete_existing_tag_release:
    description: 'Is this a re-release of existing tag/release? (Default: false)'
    default: 'false'
    required: false
  github_token:
    description: 'GitHub token for creating releases'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Check if tag exists
      if: ${{ inputs.delete_existing_tag_release == 'true' }}
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        git fetch origin
        if git tag --list $VERSION_NUMBER
        then
            echo "Deleting existing tag for $VERSION_NUMBER"
            git push origin --delete tags/$VERSION_NUMBER
        fi

    - name: Check if release exists
      if: ${{ inputs.delete_existing_tag_release == 'true' }}
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 23F3D4EA75716059
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt-get install gh
        if gh release list | grep $VERSION_NUMBER
        then
            echo "Deleting existing release for $VERSION_NUMBER"
            gh release delete --yes $VERSION_NUMBER
        fi

    - name: Configure git identity
      shell: bash
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com

    - name: Update version number in manifest.yml
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        BRANCH: ${{ inputs.branch }}
      run: |
        if [ -f "./manifest.yml" ]; then
          sed -i -b "0,/^version/s/^version.*/version: \"$VERSION_NUMBER\"/g" ./manifest.yml
          git add manifest.yml
          git commit -m '[AUTO][RELEASE]: Update version number in manifest.yml'
          git push origin "$BRANCH"
        fi

    - name: Update version number in doxygen
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        BRANCH: ${{ inputs.branch }}
      run: |
        if [ -f "./docs/doxygen/config.doxyfile" ]; then
          sed -i -b "s/PROJECT_NUMBER *=.*/PROJECT_NUMBER         = $VERSION_NUMBER/g" ./docs/doxygen/config.doxyfile
          git add docs/doxygen/config.doxyfile
          git commit -m '[AUTO][RELEASE]: Update version number in doxygen'
          git push origin "$BRANCH"
        fi

    - name: Tag and push
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        git tag "$VERSION_NUMBER" -a -m "$REPO_NAME Library $VERSION_NUMBER"
        git push origin --tags

    - name: Install ZIP tools
      shell: bash
      run: sudo apt-get install zip unzip

    - name: Checkout code for ZIP
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.version_number }}
        path: ${{ github.event.repository.name }}
        submodules: recursive

    - name: Checkout disabled submodules
      shell: bash
      run: |
        cd ${{ github.event.repository.name }}
        git submodule update --init --checkout --recursive

    - name: Debug source path
      shell: bash
      env:
        SOURCE_PATH: ./${{ github.event.repository.name }}/source
      run: |
        echo "Source path: $SOURCE_PATH"
        echo "Contents of source directory:"
        ls -la "$SOURCE_PATH"

    - name: Generate SBOM for ZIP
      uses: jasonpcarroll/CI-CD-Github-Actions/sbom-generator@main
      with:
        repo_path: ./${{ github.event.repository.name }}
        source_path: ./source

    - name: Create ZIP
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        zip -r "$REPO_NAME-$VERSION_NUMBER.zip" "$REPO_NAME" -x "*.git*"

    - name: Validate created ZIP
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        mkdir zip-check
        mv "$REPO_NAME-$VERSION_NUMBER.zip" zip-check
        cd zip-check
        unzip "$REPO_NAME-$VERSION_NUMBER.zip" -d "$REPO_NAME-$VERSION_NUMBER"
        diff -r -x "*.git*" "$REPO_NAME-$VERSION_NUMBER"/"$REPO_NAME"/ ../"$REPO_NAME"/

    - name: Check version number in manifest.yml
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        cd zip-check/"$REPO_NAME-$VERSION_NUMBER"/"$REPO_NAME"
        if [ -f "./manifest.yml" ]; then
          MANIFEST_VERSION_NUMBER=$(grep -m 1 -E "^version:[ ]*\".*\"[ ]*" manifest.yml | awk -F: '{ gsub(" ","",$2); gsub("\"","",$2); print $2 }')
          [[ $MANIFEST_VERSION_NUMBER == $VERSION_NUMBER ]] \
          && echo "manifest.yml : match $VERSION_NUMBER" \
          || { echo "manifest.yml : $MANIFEST_VERSION_NUMBER doesn't match $VERSION_NUMBER"; exit 255; }
        fi

    - name: Build and test
      shell: bash
      env:
        VERSION_NUMBER: ${{ inputs.version_number }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        cd zip-check/"$REPO_NAME-$VERSION_NUMBER"/"$REPO_NAME"
        if [ -d "test" ]; then
          sudo apt-get install -y lcov
          cmake -S test -B build/ \
          -G "Unix Makefiles" \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_CLONE_SUBMODULES=ON \
          -DCMAKE_C_FLAGS='--coverage -Wall -Wextra -Werror'
          make -C build/ all
          cd build/
          ctest -E system --output-on-failure
          cd ..
        fi

    - name: Deploy doxygen documentation
      uses: FreeRTOS/CI-CD-Github-Actions/doxygen-generation@main
      with:
        ref: ${{ inputs.version_number }}
        add_release: "true"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ inputs.version_number }}
        release_name: ${{ inputs.version_number }}
        body: Release ${{ inputs.version_number }} of the ${{ github.event.repository.name }} Library.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zip-check/${{ github.event.repository.name }}-${{ inputs.version_number }}.zip
        asset_name: ${{ github.event.repository.name }}-${{ inputs.version_number }}.zip
        asset_content_type: application/zip

    - name: Upload SBOM Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ github.event.repository.name }}/sbom.spdx
        asset_name: sbom.spdx
        asset_content_type: text/plain
