name: 'complexity'
description: 'CI complexity check'
inputs:
  path:
    description: 'Path to repository folder to run complexity check in.'
    required: false
    default: ./
runs:
  using: "composite"
  steps: 
      - name: Setup
        run: sudo apt-get install complexity
        shell: bash
      - name: Complexity
        working-directory: ${{ inputs.path }}
        run: |
          find source/ -iname '*.c' |\
          xargs complexity --scores --threshold=0 --horrid-threshold=8
        shell: bash
