name: 'complexity'
description: 'CI complexity check'
inputs:
  path:
    description: 'Path to repository folder to run complexity check in.'
    required: false
    default: ./
  source_path:
    description: 'Path to the folder in the repository containing the source code.'
    required: false
    default: source
  horrid_threshold:
    description: 'The horrid threshold parameter passed to the invocation of complexity'
    required: false
    default: 10

runs:
  using: "composite"
  steps:
    - env:
        stepName: Install Dependencies
        bashPass: \033[32;1mPASSED -
        bashInfo: \033[33;1mINFO -
        bashFail: \033[31;1mFAILED -
        bashEnd:  \033[0
      name: ${{ env.stepName }}
      shell: bash
      run: |
        # ${{ env.stepName }}
        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
        sudo apt-get install complexity -y
        echo -e "::endgroup::"
        echo -e "${{ env.bashPass }} ${{env.stepName }} ${{ env.bashEnd }}"

    - env:
        stepName: Complexity
        bashPass: \033[32;1mPASSED -
        bashInfo: \033[33;1mINFO -
        bashFail: \033[31;1mFAILED -
        bashEnd:  \033[0m
      name: ${{ env.stepName }}
      working-directory: ${{ inputs.path }}
      shell: bash
      run: |
        # ${{ env.stepName }}
        echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
        echo -e "${{ env.bashInfo }} Have complexity limit of ${{ inputs.horrid_threshold }} ${{ env.bashEnd }}"
        exitStatus=0

        # Use find to find all files ending with a .c inside of the input directory
        # From there run the complexity check against them
        find ${{ inputs.source_path }}/ -iname '*.c' |\
          xargs complexity --scores --threshold=0 --horrid-threshold=${{ inputs.horrid_threshold }}

        echo -e "::endgroup::"
        echo -e "${{ env.bashPass }} ${{env.stepName }} ${{ env.bashEnd }}"
        exit 0
