name: 'complexity'
description: 'CI complexity check'
inputs:
  path:
    description: 'Path to repository folder to run complexity check in.'
    required: false
    default: ./
  source_path:
    description: 'Path to the folder in the repository containing the source code.'
    required: false
    default: source
runs:
  using: "composite"
  steps: 
      - name: Setup
        run: sudo apt-get install complexity
        shell: bash
      - name: Complexity
        working-directory: ${{ inputs.path }}
        run: |
          find ${{ inputs.source_path }}/ -iname '*.c' |\
          xargs complexity --scores --threshold=0 --horrid-threshold=8
        shell: bash
