name: 'doxygen'
description: 'Check doxygen build and optionally, generate ZIP'
inputs:
  path:
    description: 'Path to repository folder to run doxygen generation in.'
    required: false
    default: ./
  libs_parent_dir_path:
    description: 'Comma-separated list of parent directory path of libraries. Path should be relative to repository root.'
    required: false
    default: ./
  doxygen_link:
    description: 'Download link for doxygen tar.gz (default version 1.8.20).'
    required: false
    default: "https://sourceforge.net/projects/doxygen/files/rel-1.8.20/doxygen-1.8.20.linux.bin.tar.gz"
  generate_zip:
    description: 'Flag to indicate whether a ZIP output should be created.'
    required: false
    default: 'false'
  
runs:
  using: "composite"
  steps:
    - name: Install Doxygen
      run: |
        wget -qO- "${{ inputs.doxygen_link }}" | sudo tar --strip-components=1 -xz -C /usr/local
        sudo apt-get install -y libclang-9-dev graphviz
      shell: bash
    - name: If specified, generate doxygen ZIP output
      if: ${{ inputs.generate_zip }} == "true"
      working-directory: ${{ inputs.path }}
      run: |
        python3 $GITHUB_ACTION_PATH/generate_doxygen.py --root ./ --library-directories ${{ inputs.libs_parent_dir_path }} --zip
      shell: bash
    - name: Check doxygen build and verify stdout is empty.
      if: ${{ inputs.generate_zip }} == "false"
      working-directory: ${{ inputs.path }}
      run: |
          doxygen docs/doxygen/config.doxyfile 2>&1 | tee doxyoutput.txt
          if [[ "$(wc -c < doxyoutput.txt | bc)" = "0" ]]; then exit 0; else exit 1; fi
      shell: bash
